version: "2"

services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: lat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - databases_net
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lat -U admin"]

  server:
    image: server:1
    container_name: server
    networks:
      - databases_net
    volumes:
      - server_vol:/app
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:80 || exit 1"]
    depends_on:
      - postgres

volumes:
  postgres_vol:
  server_vol:

networks:
  databases_net: